"""Updated embedding size on db from 764 to 768

Revision ID: 1f082f73d58b
Revises: 5d8ef3bb67f4
Create Date: 2026-08-25 12:30:45.595871

"""

from typing import Sequence, Union

from pgvector.sqlalchemy.vector import VECTOR

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f082f73d58b"
down_revision: Union[str, Sequence[str], None] = "5d8ef3bb67f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=VECTOR(dim=764),
        type_=VECTOR(dim=768),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=VECTOR(dim=768),
        type_=VECTOR(dim=764),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
