"""Add Ticket, ItTicket, and HrRequest tables

Revision ID: 2530d85e8b36
Revises: d95b7c87d545
Create Date: 2026-07-20 15:17:11.124965

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2530d85e8b36"
down_revision: Union[str, Sequence[str], None] = "d95b7c87d545"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("poster_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("HR_REQUEST", "IT_TICKET", name="ticket_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "PENDING", "RESOLVED", "CLOSED", name="ticket_status"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="ticket_priority"),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("information", sa.Text(), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["poster_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hr_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "request_type",
            sa.Enum("LEAVE_REQUEST", "DOCUMENT_REQUEST", name="request_type"),
            nullable=False,
        ),
        sa.Column(
            "document_type",
            sa.Enum("NOC", "SALARY_CERTIFICATE", name="document_type"),
            nullable=True,
        ),
        sa.Column("from_date", sa.Date(), nullable=True),
        sa.Column("to_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "it_tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "request_type",
            sa.Enum("HARDWARE_ISSUE", "SOFTWARE_ISSUE", name="it_request_type"),
            nullable=False,
        ),
        sa.Column("device_type", sa.String(length=100), nullable=True),
        sa.Column("fault_code", sa.String(length=4), nullable=True),
        sa.Column("software_name", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("it_tickets")
    op.drop_table("hr_requests")
    op.drop_table("tickets")

    sa.Enum(name="ticket_type").drop(op.get_bind())
    sa.Enum(name="ticket_status").drop(op.get_bind())
    sa.Enum(name="ticket_priority").drop(op.get_bind())
    sa.Enum(name="request_type").drop(op.get_bind())
    sa.Enum(name="document_type").drop(op.get_bind())
    sa.Enum(name="it_request_type").drop(op.get_bind())
    # ### end Alembic commands ###
