"""changed dimensions from 748 to 1024 to support cohere

Revision ID: 4560330e5ec2
Revises: 87293d0c30dc
Create Date: 2026-09-13 13:05:39.248546

"""

from typing import Sequence, Union

from pgvector.sqlalchemy import vector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4560330e5ec2"
down_revision: Union[str, Sequence[str], None] = "87293d0c30dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=vector.VECTOR(dim=768),
        type_=vector.VECTOR(dim=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=vector.VECTOR(dim=1024),
        type_=vector.VECTOR(dim=768),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
