"""replace_password_hash_with_cognito_sub

Revision ID: 531241929c87
Revises: 9000890e72ea
Create Date: 2026-08-02 14:58:40.338989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531241929c87'
down_revision: Union[str, Sequence[str], None] = '9000890e72ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cognito_sub', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'users', ['cognito_sub'])
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cognito_sub')
    # ### end Alembic commands ###
