"""updated chat_sessions and chat_message to be timezone aware

Revision ID: 593e8f7dab2d
Revises: 86a1803a365f
Create Date: 2026-09-02 11:15:16.519462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '593e8f7dab2d'
down_revision: Union[str, Sequence[str], None] = '86a1803a365f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('chat_session_id', sa.Uuid(), nullable=False))
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_chat_session_id'), 'chat_messages', ['chat_session_id'], unique=False)
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['chat_session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'session_id')
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.drop_column('chat_sessions', 'ttl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('ttl', postgresql.TIMESTAMP(), server_default=sa.text('(now() + make_interval(secs => (86400.0)::double precision))'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('chat_messages', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_chat_session_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('chat_messages', 'chat_session_id')
    # ### end Alembic commands ###
