"""Add documents table

Revision ID: 63b1d1c21d01
Revises: a1b2c3d4e5f6
Create Date: 2026-08-20 08:00:20.869224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b1d1c21d01'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=False),
    sa.Column('s3_bucket', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('HR_POLICY', 'IT_MANUAL', name='document_category'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
