"""Increased fault_code length from 4 to 20

Revision ID: 68c56ed90c1b
Revises: 531241929c87
Create Date: 2026-08-03 16:16:48.258213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c56ed90c1b'
down_revision: Union[str, Sequence[str], None] = '531241929c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('it_tickets', 'fault_code',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('it_tickets', 'fault_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###
