"""make user department nullable

Revision ID: 9000890e72ea
Revises: 8d41560dd36b
Create Date: 2026-07-31 14:42:01.173584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9000890e72ea'
down_revision: Union[str, Sequence[str], None] = '8d41560dd36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('employee', 'admin', name='user_role'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'department',
               existing_type=postgresql.ENUM('HR', 'IT', 'OTHER', name='user_department'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department',
               existing_type=postgresql.ENUM('HR', 'IT', 'OTHER', name='user_department'),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('employee', 'admin', name='user_role'),
               server_default=sa.text("'employee'::user_role"),
               existing_nullable=False)
    # ### end Alembic commands ###
