/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminHrRouteRouteImport } from './routes/_authenticated/admin/hr/route'
import { Route as AuthenticatedAdminItRouteRouteImport } from './routes/_authenticated/admin/it/route'
import { Route as AuthenticatedEmployeeIndexRouteImport } from './routes/_authenticated/employee/index'
import { Route as AuthenticatedKbIndexRouteImport } from './routes/_authenticated/kb/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedTicketSubmitRouteImport } from './routes/_authenticated/ticket/submit'
import { Route as AuthenticatedAdminItTicketsRouteImport } from './routes/_authenticated/admin/it/tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminHrRouteRoute =
  AuthenticatedAdminHrRouteRouteImport.update({
    id: '/hr',
    path: '/hr',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminItRouteRoute =
  AuthenticatedAdminItRouteRouteImport.update({
    id: '/it',
    path: '/it',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedEmployeeIndexRoute =
  AuthenticatedEmployeeIndexRouteImport.update({
    id: '/employee/',
    path: '/employee/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKbIndexRoute = AuthenticatedKbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketSubmitRoute =
  AuthenticatedTicketSubmitRouteImport.update({
    id: '/ticket/submit',
    path: '/ticket/submit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminItTicketsRoute =
  AuthenticatedAdminItTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminItRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/hr': typeof AuthenticatedAdminHrRouteRoute
  '/admin/it': typeof AuthenticatedAdminItRouteRouteWithChildren
  '/ticket/submit': typeof AuthenticatedTicketSubmitRoute
  '/employee/': typeof AuthenticatedEmployeeIndexRoute
  '/kb/': typeof AuthenticatedKbIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/admin/it/tickets': typeof AuthenticatedAdminItTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/hr': typeof AuthenticatedAdminHrRouteRoute
  '/admin/it': typeof AuthenticatedAdminItRouteRouteWithChildren
  '/ticket/submit': typeof AuthenticatedTicketSubmitRoute
  '/employee': typeof AuthenticatedEmployeeIndexRoute
  '/kb': typeof AuthenticatedKbIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/admin/it/tickets': typeof AuthenticatedAdminItTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/hr': typeof AuthenticatedAdminHrRouteRoute
  '/_authenticated/admin/it': typeof AuthenticatedAdminItRouteRouteWithChildren
  '/_authenticated/ticket/submit': typeof AuthenticatedTicketSubmitRoute
  '/_authenticated/employee/': typeof AuthenticatedEmployeeIndexRoute
  '/_authenticated/kb/': typeof AuthenticatedKbIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/admin/it/tickets': typeof AuthenticatedAdminItTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/admin/hr'
    | '/admin/it'
    | '/ticket/submit'
    | '/employee/'
    | '/kb/'
    | '/profile/'
    | '/admin/it/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/admin/hr'
    | '/admin/it'
    | '/ticket/submit'
    | '/employee'
    | '/kb'
    | '/profile'
    | '/admin/it/tickets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/admin/hr'
    | '/_authenticated/admin/it'
    | '/_authenticated/ticket/submit'
    | '/_authenticated/employee/'
    | '/_authenticated/kb/'
    | '/_authenticated/profile/'
    | '/_authenticated/admin/it/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/hr': {
      id: '/_authenticated/admin/hr'
      path: '/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AuthenticatedAdminHrRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/it': {
      id: '/_authenticated/admin/it'
      path: '/it'
      fullPath: '/admin/it'
      preLoaderRoute: typeof AuthenticatedAdminItRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/employee/': {
      id: '/_authenticated/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof AuthenticatedEmployeeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kb/': {
      id: '/_authenticated/kb/'
      path: '/kb'
      fullPath: '/kb/'
      preLoaderRoute: typeof AuthenticatedKbIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ticket/submit': {
      id: '/_authenticated/ticket/submit'
      path: '/ticket/submit'
      fullPath: '/ticket/submit'
      preLoaderRoute: typeof AuthenticatedTicketSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/it/tickets': {
      id: '/_authenticated/admin/it/tickets'
      path: '/tickets'
      fullPath: '/admin/it/tickets'
      preLoaderRoute: typeof AuthenticatedAdminItTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminItRouteRoute
    }
  }
}

interface AuthenticatedAdminItRouteRouteChildren {
  AuthenticatedAdminItTicketsRoute: typeof AuthenticatedAdminItTicketsRoute
}

const AuthenticatedAdminItRouteRouteChildren: AuthenticatedAdminItRouteRouteChildren =
  {
    AuthenticatedAdminItTicketsRoute: AuthenticatedAdminItTicketsRoute,
  }

const AuthenticatedAdminItRouteRouteWithChildren =
  AuthenticatedAdminItRouteRoute._addFileChildren(
    AuthenticatedAdminItRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminHrRouteRoute: typeof AuthenticatedAdminHrRouteRoute
  AuthenticatedAdminItRouteRoute: typeof AuthenticatedAdminItRouteRouteWithChildren
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminHrRouteRoute: AuthenticatedAdminHrRouteRoute,
    AuthenticatedAdminItRouteRoute: AuthenticatedAdminItRouteRouteWithChildren,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedTicketSubmitRoute: typeof AuthenticatedTicketSubmitRoute
  AuthenticatedEmployeeIndexRoute: typeof AuthenticatedEmployeeIndexRoute
  AuthenticatedKbIndexRoute: typeof AuthenticatedKbIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedTicketSubmitRoute: AuthenticatedTicketSubmitRoute,
  AuthenticatedEmployeeIndexRoute: AuthenticatedEmployeeIndexRoute,
  AuthenticatedKbIndexRoute: AuthenticatedKbIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
