/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeRouteRouteImport } from './routes/employee/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminDepartmentRouteRouteImport } from './routes/admin/$department/route'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as EmployeeKbRouteImport } from './routes/employee/kb'
import { Route as EmployeeProfileRouteImport } from './routes/employee/profile'
import { Route as EmployeeTicketSubmitRouteImport } from './routes/employee/ticket.submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRouteRoute = EmployeeRouteRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentRouteRoute = AdminDepartmentRouteRouteImport.update({
  id: '/admin/$department',
  path: '/admin/$department',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeKbRoute = EmployeeKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRouteRoute,
} as any)
const EmployeeTicketSubmitRoute = EmployeeTicketSubmitRouteImport.update({
  id: '/ticket/submit',
  path: '/ticket/submit',
  getParentRoute: () => EmployeeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/$department': typeof AdminDepartmentRouteRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/employee/kb': typeof EmployeeKbRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/': typeof EmployeeIndexRoute
  '/employee/ticket/submit': typeof EmployeeTicketSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$department': typeof AdminDepartmentRouteRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/employee/kb': typeof EmployeeKbRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee': typeof EmployeeIndexRoute
  '/employee/ticket/submit': typeof EmployeeTicketSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/$department': typeof AdminDepartmentRouteRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/employee/kb': typeof EmployeeKbRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/': typeof EmployeeIndexRoute
  '/employee/ticket/submit': typeof EmployeeTicketSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/login'
    | '/admin/$department'
    | '/admin/tickets'
    | '/employee/kb'
    | '/employee/profile'
    | '/employee/'
    | '/employee/ticket/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/$department'
    | '/admin/tickets'
    | '/employee/kb'
    | '/employee/profile'
    | '/employee'
    | '/employee/ticket/submit'
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/login'
    | '/admin/$department'
    | '/admin/tickets'
    | '/employee/kb'
    | '/employee/profile'
    | '/employee/'
    | '/employee/ticket/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRouteRoute: typeof EmployeeRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AdminDepartmentRouteRoute: typeof AdminDepartmentRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$department': {
      id: '/admin/$department'
      path: '/admin/$department'
      fullPath: '/admin/$department'
      preLoaderRoute: typeof AdminDepartmentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/kb': {
      id: '/employee/kb'
      path: '/kb'
      fullPath: '/employee/kb'
      preLoaderRoute: typeof EmployeeKbRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
    '/employee/ticket/submit': {
      id: '/employee/ticket/submit'
      path: '/ticket/submit'
      fullPath: '/employee/ticket/submit'
      preLoaderRoute: typeof EmployeeTicketSubmitRouteImport
      parentRoute: typeof EmployeeRouteRoute
    }
  }
}

interface EmployeeRouteRouteChildren {
  EmployeeKbRoute: typeof EmployeeKbRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  EmployeeTicketSubmitRoute: typeof EmployeeTicketSubmitRoute
}

const EmployeeRouteRouteChildren: EmployeeRouteRouteChildren = {
  EmployeeKbRoute: EmployeeKbRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  EmployeeTicketSubmitRoute: EmployeeTicketSubmitRoute,
}

const EmployeeRouteRouteWithChildren = EmployeeRouteRoute._addFileChildren(
  EmployeeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRouteRoute: EmployeeRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AdminDepartmentRouteRoute: AdminDepartmentRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
